spring:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none
    show-sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver