name: Java CI with Gradle & Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Make Gradlew executable
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Archive build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: jar-files
        path: build/libs/game-0.0.1-SNAPSHOT.jar # 빌드된 JAR 파일명에 맞게 수정

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v2
      with:
        name: jar-files
        path: ${{ github.workspace }}/tmp # 다운로드 받을 디렉토리를 workspace 내 tmp 디렉토리로 변경합니다.

    - name: Copy JAR to server
      run: scp -i ${{ secrets.SERVER_SSH_KEY }} -P ${{ secrets.SERVER_PORT }} /tmp/game-0.0.1-SNAPSHOT.jar ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:/path/to/deployment/directory/

    - name: SSH into server and restart application
      run: |
        ssh -i ${{ secrets.SERVER_SSH_KEY }} -p ${{ secrets.SERVER_PORT }} ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} << 'EOF'
          cd /path/to/deployment/directory/
          pkill -f "java -jar game-0.0.1-SNAPSHOT.jar"
          nohup java -jar game-0.0.1-SNAPSHOT.jar &
        EOF
