name: Java CI with Gradle & Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    - name: Make Gradlew executable
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Archive build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: jar-files
        path: build/libs/game-0.0.1-SNAPSHOT.jar # 빌드된 JAR 파일명에 맞게 수정

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v2
      with:
        name: jar-files
        path: /tmp

    - name: Copy JAR to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        source: "/tmp/game-0.0.1-SNAPSHOT.jar" # 빌드된 JAR 파일명에 맞게 수정
        target: "/path/to/deployment/directory/"

    - name: SSH into server and restart application
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          cd /path/to/deployment/directory/
          # 이전 프로세스 종료
          pkill -f "java -jar game-0.0.1-SNAPSHOT.jar" # 빌드된 JAR 파일명에 맞게 수정
          # 새로운 프로세스 실행
          nohup java -jar game-0.0.1-SNAPSHOT.jar & # 빌드된 JAR 파일명에 맞게 수정
