name: Java CI with Gradle & Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Make Gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: jar-files
          path: build/libs/game-0.0.1-SNAPSHOT.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: jar-files
          path: ${{ github.workspace }}/tmp

      - name: Copy JAR to server
        run: scp -i ${{ secrets.SERVER_SSH_KEY }} -P ${{ secrets.SERVER_PORT }} ${{ github.workspace }}/tmp/game-0.0.1-SNAPSHOT.jar ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:/path/to/deployment/directory/

      - name: SSH into server and restart application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd /path/to/deployment/directory/
            pkill -f "java -jar game-0.0.1-SNAPSHOT.jar"
            nohup java -jar game-0.0.1-SNAPSHOT.jar &
